// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tabatine.Infrastructure.Data;

#nullable disable

namespace Tabatine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331183134_AddCreatedAtToPerfil")]
    partial class AddCreatedAtToPerfil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tabatine.Core.Entities.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_banco");

                    b.Property<string>("CodigoIspb")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_ispb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bancos");

                    b.HasIndex("CodigoBanco")
                        .IsUnique()
                        .HasDatabaseName("ix_bancos_codigo_banco");

                    b.ToTable("bancos", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj_cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endereco");

                    b.Property<string>("EnderecoComplemento")
                        .HasColumnType("text")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("text")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<bool>("OptanteSimplesNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("optante_simples_nacional");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_omie_id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.CondicaoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<int>("DiaFixo")
                        .HasColumnType("integer")
                        .HasColumnName("dia_fixo");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_condicoes_pagamento");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_condicoes_pagamento_codigo");

                    b.ToTable("condicoes_pagamento", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("banco_id");

                    b.Property<string>("CodigoIntegracao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_integracao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Inativa")
                        .HasColumnType("boolean")
                        .HasColumnName("inativa");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contas_corrente");

                    b.HasIndex("BancoId")
                        .HasDatabaseName("ix_contas_corrente_banco_id");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_corrente_omie_id");

                    b.ToTable("contas_corrente", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.EtapaFaturamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_operacao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("DescricaoOperacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao_operacao");

                    b.Property<string>("DescricaoPadrao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao_padrao");

                    b.Property<bool>("Inativa")
                        .HasColumnType("boolean")
                        .HasColumnName("inativa");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_etapas_faturamento");

                    b.HasIndex("CodigoOperacao", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_faturamento_codigo_operacao_codigo");

                    b.ToTable("etapas_faturamento", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DiasParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("dias_parcelas");

                    b.Property<string>("ListaParcelas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("lista_parcelas");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_formas_pagamento");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_formas_pagamento_codigo");

                    b.ToTable("formas_pagamento", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.IntegrationSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSyncDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_date");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_integration_sync_states");

                    b.ToTable("integration_sync_states", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemNotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AliqCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_cbs");

                    b.Property<decimal>("AliqIbs")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_ibs");

                    b.Property<decimal>("AliqIcms")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_icms");

                    b.Property<decimal>("AliqIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_ipi");

                    b.Property<decimal>("BaseIbsCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("base_ibs_cbs");

                    b.Property<decimal>("BaseIcms")
                        .HasColumnType("numeric")
                        .HasColumnName("base_icms");

                    b.Property<decimal>("BaseIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("base_ipi");

                    b.Property<string>("Cfop")
                        .HasColumnType("text")
                        .HasColumnName("cfop");

                    b.Property<string>("CstIcms")
                        .HasColumnType("text")
                        .HasColumnName("cst_icms");

                    b.Property<string>("CstIpi")
                        .HasColumnType("text")
                        .HasColumnName("cst_ipi");

                    b.Property<string>("Ncm")
                        .HasColumnType("text")
                        .HasColumnName("ncm");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_cbs");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_cofins");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_ibs");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_ipi");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_pis");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_itens_nota_fiscal");

                    b.HasIndex("NotaFiscalId")
                        .HasDatabaseName("ix_itens_nota_fiscal_nota_fiscal_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_nota_fiscal_produto_id");

                    b.ToTable("itens_nota_fiscal", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AliqCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_cbs");

                    b.Property<decimal>("AliqCofins")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_cofins");

                    b.Property<decimal>("AliqIbs")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_ibs");

                    b.Property<decimal>("AliqIcms")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_icms");

                    b.Property<decimal>("AliqIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_ipi");

                    b.Property<decimal>("AliqPis")
                        .HasColumnType("numeric")
                        .HasColumnName("aliq_pis");

                    b.Property<decimal>("BaseCofins")
                        .HasColumnType("numeric")
                        .HasColumnName("base_cofins");

                    b.Property<decimal>("BaseIbsCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("base_ibs_cbs");

                    b.Property<decimal>("BaseIcms")
                        .HasColumnType("numeric")
                        .HasColumnName("base_icms");

                    b.Property<decimal>("BaseIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("base_ipi");

                    b.Property<decimal>("BasePis")
                        .HasColumnType("numeric")
                        .HasColumnName("base_pis");

                    b.Property<string>("Cfop")
                        .HasColumnType("text")
                        .HasColumnName("cfop");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CstCofins")
                        .HasColumnType("text")
                        .HasColumnName("cst_cofins");

                    b.Property<string>("CstIcms")
                        .HasColumnType("text")
                        .HasColumnName("cst_icms");

                    b.Property<string>("CstIpi")
                        .HasColumnType("text")
                        .HasColumnName("cst_ipi");

                    b.Property<string>("CstPis")
                        .HasColumnType("text")
                        .HasColumnName("cst_pis");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<Guid>("PedidoVendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_venda_id");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentual_desconto");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("peso_bruto");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("peso_liquido");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade_medida");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_cbs");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cofins");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_ibs");

                    b.Property<decimal>("ValorIcms")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_icms");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_ipi");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pis");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_itens_pedido");

                    b.HasIndex("PedidoVendaId")
                        .HasDatabaseName("ix_itens_pedido_pedido_venda_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_pedido_produto_id");

                    b.ToTable("itens_pedido", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("LogEvent")
                        .HasColumnType("text")
                        .HasColumnName("log_event");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.MeioPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meios_pagamento");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_meios_pagamento_omie_id");

                    b.ToTable("meios_pagamento", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .HasColumnType("text")
                        .HasColumnName("ambiente");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_acesso");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<int>("CodigoStatus")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_status");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_corrente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_saida");

                    b.Property<bool>("Denegada")
                        .HasColumnType("boolean")
                        .HasColumnName("denegada");

                    b.Property<string>("Finalidade")
                        .HasColumnType("text")
                        .HasColumnName("finalidade");

                    b.Property<TimeSpan?>("HoraEmissao")
                        .HasColumnType("interval")
                        .HasColumnName("hora_emissao");

                    b.Property<TimeSpan?>("HoraSaida")
                        .HasColumnType("interval")
                        .HasColumnName("hora_saida");

                    b.Property<decimal>("IcmsBaseCalculo")
                        .HasColumnType("numeric")
                        .HasColumnName("icms_base_calculo");

                    b.Property<decimal>("IcmsValor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("icms_valor");

                    b.Property<long?>("IdTransportadora")
                        .HasColumnType("bigint")
                        .HasColumnName("id_transportadora");

                    b.Property<bool>("ImportadoApi")
                        .HasColumnType("boolean")
                        .HasColumnName("importado_api");

                    b.Property<string>("InformacoesComplementares")
                        .HasColumnType("text")
                        .HasColumnName("informacoes_complementares");

                    b.Property<string>("InformacoesFisco")
                        .HasColumnType("text")
                        .HasColumnName("informacoes_fisco");

                    b.Property<decimal>("IssqnBaseCalculo")
                        .HasColumnType("numeric")
                        .HasColumnName("issqn_base_calculo");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("NaturezaOperacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("natureza_operacao");

                    b.Property<string>("NumeroNf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nf");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<Guid?>("PedidoVendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_venda_id");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoOperacao")
                        .HasColumnType("text")
                        .HasColumnName("tipo_operacao");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cbs");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_cofins");

                    b.Property<decimal>("ValorCofinsRetido")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cofins_retido");

                    b.Property<decimal>("ValorCsll")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_csll");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_frete");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_ibs");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_ipi");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_ir");

                    b.Property<decimal>("ValorIss")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_iss");

                    b.Property<decimal>("ValorOutrasDespesas")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_outras_despesas");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_pis");

                    b.Property<decimal>("ValorPisRetido")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pis_retido");

                    b.Property<decimal>("ValorProd")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_prod");

                    b.Property<decimal>("ValorSeguro")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_seguro");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_fiscais");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_notas_fiscais_cliente_id");

                    b.HasIndex("ContaCorrenteId")
                        .HasDatabaseName("ix_notas_fiscais_conta_corrente_id");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_fiscais_omie_id");

                    b.HasIndex("PedidoVendaId")
                        .HasDatabaseName("ix_notas_fiscais_pedido_venda_id");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_notas_fiscais_vendedor_id");

                    b.ToTable("notas_fiscais", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscalTitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_corrente_id");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<long?>("OmieIdTitulo")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id_titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_nota_fiscal_titulos");

                    b.HasIndex("ContaCorrenteId")
                        .HasDatabaseName("ix_nota_fiscal_titulos_conta_corrente_id");

                    b.HasIndex("NotaFiscalId")
                        .HasDatabaseName("ix_nota_fiscal_titulos_nota_fiscal_id");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_nota_fiscal_titulos_vendedor_id");

                    b.ToTable("nota_fiscal_titulos", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoParcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_corrente_id");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid?>("MeioPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("meio_pagamento_id");

                    b.Property<string>("Nsu")
                        .HasColumnType("text")
                        .HasColumnName("nsu");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<Guid>("PedidoVendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_venda_id");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentual");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pedido_parcelas");

                    b.HasIndex("ContaCorrenteId")
                        .HasDatabaseName("ix_pedido_parcelas_conta_corrente_id");

                    b.HasIndex("MeioPagamentoId")
                        .HasDatabaseName("ix_pedido_parcelas_meio_pagamento_id");

                    b.HasIndex("PedidoVendaId")
                        .HasDatabaseName("ix_pedido_parcelas_pedido_venda_id");

                    b.ToTable("pedido_parcelas", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Autorizado")
                        .HasColumnType("boolean")
                        .HasColumnName("autorizado");

                    b.Property<decimal>("BaseCalculoIcms")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_calculo_icms");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelado");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoParcela")
                        .HasColumnType("text")
                        .HasColumnName("codigo_parcela");

                    b.Property<string>("CodigoRastreio")
                        .HasColumnType("text")
                        .HasColumnName("codigo_rastreio");

                    b.Property<decimal>("ComissaoVendedor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("comissao_vendedor");

                    b.Property<Guid?>("CondicaoPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("condicao_pagamento_id");

                    b.Property<string>("ConsumidorFinal")
                        .HasColumnType("text")
                        .HasColumnName("consumidor_final");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_corrente_id");

                    b.Property<string>("Contato")
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DadosAdicionaisNf")
                        .HasColumnType("text")
                        .HasColumnName("dados_adicionais_nf");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_previsao");

                    b.Property<bool>("Denegado")
                        .HasColumnType("boolean")
                        .HasColumnName("denegado");

                    b.Property<bool>("Devolvido")
                        .HasColumnType("boolean")
                        .HasColumnName("devolvido");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etapa");

                    b.Property<Guid?>("EtapaFaturamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_faturamento_id");

                    b.Property<bool>("Faturado")
                        .HasColumnType("boolean")
                        .HasColumnName("faturado");

                    b.Property<Guid?>("FormaPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<string>("FreteModalidade")
                        .HasColumnType("text")
                        .HasColumnName("frete_modalidade");

                    b.Property<string>("LinkRastreio")
                        .HasColumnType("text")
                        .HasColumnName("link_rastreio");

                    b.Property<string>("MeioPagamento")
                        .HasColumnType("text")
                        .HasColumnName("meio_pagamento");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_pedido");

                    b.Property<string>("NumeroPedidoCliente")
                        .HasColumnType("text")
                        .HasColumnName("numero_pedido_cliente");

                    b.Property<string>("ObservacoesInternas")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_internas");

                    b.Property<string>("ObservacoesVenda")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_venda");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("peso_bruto");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("peso_liquido");

                    b.Property<string>("Placa")
                        .HasColumnType("text")
                        .HasColumnName("placa");

                    b.Property<DateTime?>("PrevisaoEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previsao_entrega");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<int>("QuantidadeVolumes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_volumes");

                    b.Property<string>("Transportadora")
                        .HasColumnType("text")
                        .HasColumnName("transportadora");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_alteracao");

                    b.Property<string>("UsuarioInclusao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_inclusao");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cbs");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cofins");

                    b.Property<decimal>("ValorCsll")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_csll");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_frete");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_ibs");

                    b.Property<decimal>("ValorIcms")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_icms");

                    b.Property<decimal>("ValorInss")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_inss");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_ipi");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_ir");

                    b.Property<decimal>("ValorIss")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_iss");

                    b.Property<decimal>("ValorMercadorias")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_mercadorias");

                    b.Property<decimal>("ValorOutrasDespesas")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_outras_despesas");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pis");

                    b.Property<decimal>("ValorSeguro")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_seguro");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<string>("VeiculoProprio")
                        .HasColumnType("text")
                        .HasColumnName("veiculo_proprio");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_venda");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_venda_cliente_id");

                    b.HasIndex("CondicaoPagamentoId")
                        .HasDatabaseName("ix_pedidos_venda_condicao_pagamento_id");

                    b.HasIndex("ContaCorrenteId")
                        .HasDatabaseName("ix_pedidos_venda_conta_corrente_id");

                    b.HasIndex("EtapaFaturamentoId")
                        .HasDatabaseName("ix_pedidos_venda_etapa_faturamento_id");

                    b.HasIndex("FormaPagamentoId")
                        .HasDatabaseName("ix_pedidos_venda_forma_pagamento_id");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_pedidos_venda_omie_id");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_pedidos_venda_vendedor_id");

                    b.ToTable("pedidos_venda", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("ReceiveLogs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("receive_logs");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<Guid?>("TelegramLinkToken")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_link_token");

                    b.Property<DateTime?>("TelegramLinkTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("telegram_link_token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_telegram_chat_id");

                    b.HasIndex("TelegramLinkToken")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_telegram_link_token");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_produto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("FamiliaProduto")
                        .HasColumnType("text")
                        .HasColumnName("familia_produto");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ncm");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso_bruto");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso_liquido");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidade_medida");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_omie_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.SyncLock", b =>
                {
                    b.Property<string>("LockKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lock_key");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LockToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lock_token");

                    b.HasKey("LockKey")
                        .HasName("pk_sync_locks");

                    b.ToTable("sync_locks", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Comissao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("comissao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Inativo")
                        .HasColumnType("boolean")
                        .HasColumnName("inativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint")
                        .HasColumnName("omie_id");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("omie_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vendedores");

                    b.HasIndex("OmieId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendedores_omie_id");

                    b.ToTable("vendedores", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("app_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event");

                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events");

                    b.ToTable("webhook_events", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contas_corrente_bancos_banco_id");

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemNotaFiscal", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_nota_fiscal_notas_fiscais_nota_fiscal_id");

                    b.HasOne("Tabatine.Core.Entities.Produto", "Produto")
                        .WithMany("ItensNotaFiscal")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_nota_fiscal_produtos_produto_id");

                    b.Navigation("NotaFiscal");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemPedido", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_pedidos_venda_pedido_venda_id");

                    b.HasOne("Tabatine.Core.Entities.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_produtos_produto_id");

                    b.Navigation("PedidoVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Cliente", "Cliente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notas_fiscais_clientes_cliente_id");

                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notas_fiscais_contas_corrente_conta_corrente_id");

                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany()
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notas_fiscais_pedidos_venda_pedido_venda_id");

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notas_fiscais_vendedores_vendedor_id");

                    b.Navigation("Cliente");

                    b.Navigation("ContaCorrente");

                    b.Navigation("PedidoVenda");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscalTitulo", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Titulos")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nota_fiscal_titulos_contas_corrente_conta_corrente_id");

                    b.HasOne("Tabatine.Core.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Titulos")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nota_fiscal_titulos_notas_fiscais_nota_fiscal_id");

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("Titulos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nota_fiscal_titulos_vendedores_vendedor_id");

                    b.Navigation("ContaCorrente");

                    b.Navigation("NotaFiscal");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoParcela", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedido_parcelas_contas_corrente_conta_corrente_id");

                    b.HasOne("Tabatine.Core.Entities.MeioPagamento", "MeioPagamento")
                        .WithMany()
                        .HasForeignKey("MeioPagamentoId")
                        .HasConstraintName("fk_pedido_parcelas_meios_pagamento_meio_pagamento_id");

                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany("Parcelas")
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_parcelas_pedidos_venda_pedido_venda_id");

                    b.Navigation("ContaCorrente");

                    b.Navigation("MeioPagamento");

                    b.Navigation("PedidoVenda");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_venda_clientes_cliente_id");

                    b.HasOne("Tabatine.Core.Entities.CondicaoPagamento", "CondicaoPagamento")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("CondicaoPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_venda_condicoes_pagamento_condicao_pagamento_id");

                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_venda_contas_corrente_conta_corrente_id");

                    b.HasOne("Tabatine.Core.Entities.EtapaFaturamento", "EtapaFaturamento")
                        .WithMany()
                        .HasForeignKey("EtapaFaturamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_venda_etapas_faturamento_etapa_faturamento_id");

                    b.HasOne("Tabatine.Core.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_venda_formas_pagamento_forma_pagamento_id");

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_venda_vendedores_vendedor_id");

                    b.Navigation("Cliente");

                    b.Navigation("CondicaoPagamento");

                    b.Navigation("ContaCorrente");

                    b.Navigation("EtapaFaturamento");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Cliente", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.CondicaoPagamento", b =>
                {
                    b.Navigation("PedidosVenda");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Parcelas");

                    b.Navigation("PedidosVenda");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Produto", b =>
                {
                    b.Navigation("ItensNotaFiscal");

                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Vendedor", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("PedidosVenda");

                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
