// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tabatine.Infrastructure.Data;

#nullable disable

namespace Tabatine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319105048_RemoveTabelasPrecos")]
    partial class RemoveTabelasPrecos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tabatine.Core.Entities.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodigoIspb")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBanco")
                        .IsUnique();

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EnderecoComplemento")
                        .HasColumnType("text");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OptanteSimplesNacional")
                        .HasColumnType("boolean");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.CondicaoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DiaFixo")
                        .HasColumnType("integer");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CondicoesPagamento");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BancoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoIntegracao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Inativa")
                        .HasColumnType("boolean");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.ToTable("ContasCorrente");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.EtapaFaturamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodigoOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescricaoOperacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescricaoPadrao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Inativa")
                        .HasColumnType("boolean");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoOperacao", "Codigo")
                        .IsUnique();

                    b.ToTable("EtapasFaturamento");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("DiasParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("ListaParcelas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.IntegrationSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IntegrationSyncStates");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemNotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AliqIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliqIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseIpi")
                        .HasColumnType("numeric");

                    b.Property<string>("Cfop")
                        .HasColumnType("text");

                    b.Property<string>("CstIcms")
                        .HasColumnType("text");

                    b.Property<string>("CstIpi")
                        .HasColumnType("text");

                    b.Property<string>("Ncm")
                        .HasColumnType("text");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensNotaFiscal", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AliqCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliqIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliqIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliqPis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BasePis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CstCofins")
                        .HasColumnType("text");

                    b.Property<string>("CstIcms")
                        .HasColumnType("text");

                    b.Property<string>("CstIpi")
                        .HasColumnType("text");

                    b.Property<string>("CstPis")
                        .HasColumnType("text");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PedidoVendaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIcms")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoVendaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("LogEvent")
                        .HasColumnType("jsonb")
                        .HasColumnName("log_event");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.MeioPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.ToTable("MeiosPagamento", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ambiente")
                        .HasColumnType("text");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("CodigoStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Denegada")
                        .HasColumnType("boolean");

                    b.Property<string>("Finalidade")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("HoraEmissao")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSaida")
                        .HasColumnType("interval");

                    b.Property<decimal>("IcmsBaseCalculo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IcmsValor")
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("IdTransportadora")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImportadoApi")
                        .HasColumnType("boolean");

                    b.Property<string>("InformacoesComplementares")
                        .HasColumnType("text");

                    b.Property<string>("InformacoesFisco")
                        .HasColumnType("text");

                    b.Property<decimal>("IssqnBaseCalculo")
                        .HasColumnType("numeric");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("NaturezaOperacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroNf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PedidoVendaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoOperacao")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorCofinsRetido")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCsll")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIss")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorOutrasDespesas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPisRetido")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorProd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorSeguro")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.HasIndex("PedidoVendaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("NotasFiscais", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscalTitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<long?>("OmieIdTitulo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("VendedorId");

                    b.ToTable("NotaFiscalTitulos", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoParcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MeioPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<Guid>("PedidoVendaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("MeioPagamentoId");

                    b.HasIndex("PedidoVendaId");

                    b.ToTable("PedidoParcelas", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Autorizado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BaseCalculoIcms")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoParcela")
                        .HasColumnType("text");

                    b.Property<string>("CodigoRastreio")
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoVendedor")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("CondicaoPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumidorFinal")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAdicionaisNf")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Denegado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Devolvido")
                        .HasColumnType("boolean");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EtapaFaturamentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Faturado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FormaPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FreteModalidade")
                        .HasColumnType("text");

                    b.Property<string>("LinkRastreio")
                        .HasColumnType("text");

                    b.Property<string>("MeioPagamento")
                        .HasColumnType("text");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPedidoCliente")
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesInternas")
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesVenda")
                        .HasColumnType("text");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PrevisaoEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeVolumes")
                        .HasColumnType("integer");

                    b.Property<string>("Transportadora")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioInclusao")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorCbs")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCofins")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorCsll")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIbs")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIcms")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorInss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIpi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorIss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMercadorias")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorOutrasDespesas")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorPis")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorSeguro")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VeiculoProprio")
                        .HasColumnType("text");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CondicaoPagamentoId");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("EtapaFaturamentoId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("PedidosVenda", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ean")
                        .HasColumnType("text");

                    b.Property<string>("FamiliaProduto")
                        .HasColumnType("text");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.SyncLock", b =>
                {
                    b.Property<string>("LockKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("LockKey");

                    b.ToTable("SyncLocks", (string)null);
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Comissao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("OmieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OmieUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OmieId")
                        .IsUnique();

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemNotaFiscal", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabatine.Core.Entities.Produto", "Produto")
                        .WithMany("ItensNotaFiscal")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaFiscal");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ItemPedido", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabatine.Core.Entities.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PedidoVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Cliente", "Cliente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany()
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("ContaCorrente");

                    b.Navigation("PedidoVenda");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscalTitulo", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Titulos")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Titulos")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("Titulos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContaCorrente");

                    b.Navigation("NotaFiscal");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoParcela", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.MeioPagamento", "MeioPagamento")
                        .WithMany()
                        .HasForeignKey("MeioPagamentoId");

                    b.HasOne("Tabatine.Core.Entities.PedidoVenda", "PedidoVenda")
                        .WithMany("Parcelas")
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");

                    b.Navigation("MeioPagamento");

                    b.Navigation("PedidoVenda");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.HasOne("Tabatine.Core.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tabatine.Core.Entities.CondicaoPagamento", "CondicaoPagamento")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("CondicaoPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.EtapaFaturamento", "EtapaFaturamento")
                        .WithMany()
                        .HasForeignKey("EtapaFaturamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tabatine.Core.Entities.Vendedor", "Vendedor")
                        .WithMany("PedidosVenda")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("CondicaoPagamento");

                    b.Navigation("ContaCorrente");

                    b.Navigation("EtapaFaturamento");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Cliente", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.CondicaoPagamento", b =>
                {
                    b.Navigation("PedidosVenda");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.ContaCorrente", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Parcelas");

                    b.Navigation("PedidosVenda");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.PedidoVenda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Produto", b =>
                {
                    b.Navigation("ItensNotaFiscal");

                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("Tabatine.Core.Entities.Vendedor", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("PedidosVenda");

                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
