<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Tabatine.Worker-f1447492-7cdb-40fb-a330-98e23e251e2a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tabatine.Infrastructure\Tabatine.Infrastructure.csproj" />
    <ProjectReference Include="..\Tabatine.Omie.Client\Tabatine.Omie.Client.csproj" />
    <ProjectReference Include="..\Tabatine.Core\Tabatine.Core.csproj" />
  </ItemGroup>
</Project>
