name: tabatine-engine
services:
  tabatine-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabatine_worker
    environment:
      - DOTNET_ENVIRONMENT=Development
    env_file:
      - .env.local
    restart: unless-stopped
    ports:
      - "8080:8080"
